// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Neon: set DIRECT_URL to the non-pooler host for migrations.
    // Local: omit DIRECT_URL — falls back to DATABASE_URL (with your password).
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
